# Cloudflare Pages + Functions configuration
name = "media-tracker"
pages_build_output_dir = "."
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding for Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "media-tracker-db"
database_id = "" # Add your D1 database ID here after creating it

# Environment variables
[vars]
NODE_ENV = "production"
