# Cloudflare Pages Configuration
name = "consumedbysr"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = ""  # No build step needed for static site
publish = "."  # Publish from root directory

# Environment variables for Pages Functions
[build.environment]
NODE_VERSION = "18"

# Headers configuration
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache configuration
[[headers]]
for = "/sw.js"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
from = "/api/*"
to = "https://media-tracker-api.2-proposal005.workers.dev/api/:splat"
status = 200